version: "3"
networks:
  proxy:
    external: true

services:
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain.1=swarm.rongyi.io
        - com.df.port.1=8080


  portainer:
    image: portainer/portainer
    command: "--host=unix:///var/run/docker.sock"
    ports:
      - "9000:9000"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain.1=docker.rongyi.io
        - com.df.port.1=9000

